### ISSUE TITLE
FastRandomIdentitySampler is not available in the repo

### ISSUE THREAD

**Issue by firatkizilirmakk** [CH-Liang/DSDML#1]
Hello,

I've read the article, it is understandable and it provides a good approach to the metric learning problems, and intended to use the offered method. Inspected the repository elaborately but I have not seen the Batch Sampler, FastRandomIdentitySampler, in the repository. It is imported from the utils directory but there is no class named like that. 

I know it is not so important but just wondered how you selected the samples for an epoch. So can you share that class too?

Thanks in advance.

**Comment by CH-Liang** [comment]
> Hello,
> 
> I've read the article, it is understandable and it provides a good approach to the metric learning problems, and intended to use the offered method. Inspected the repository elaborately but I have not seen the Batch Sampler, FastRandomIdentitySampler, in the repository. It is imported from the utils directory but there is no class named like that.
> 
> I know it is not so important but just wondered how you selected the samples for an epoch. So can you share that class too?
> 
> Thanks in advance.

I've uploaded the files and thanks for your reminding!
